import { Document } from 'src/app/shared/classes/document';

export class Inspection {
  baselineDate: Date;
  classification: string;
  comments: string;
  compliant: boolean;
  controlNumber: string;
  createdBy: string;
  discountDeadline: Date;
  discountDifference: Date;
  documents: Document[];
  facilityForm: boolean;
  frequency: number;
  globalId: string;
  id: number;
  inspectionDate: Date;
  inspectionType: string;
  inspectorId: string;
  nextInspectionDate: Date;
  receivedDate: Date;
  receivedDifference: Date;
  reducedFee: boolean;
  registrationId: number;
  registrationNumber: number;
  reviewedBy: string;
  reviewerApproved: boolean;
  siteName: string;
  supervisorApproved: boolean;
  tubeId: number;

  constructor(options: {
    baselineDate?: Date;
    classification?: string;
    comments?: string;
    compliant?: true;
    controlNumber?: string;
    createdBy?: string;
    discountDeadline?: Date;
    discountDifference?: Date;
    documents?: Document[];
    facilityForm?: boolean;
    frequency?: number;
    globalId?: string;
    id?: number;
    inspectionDate?: Date;
    inspectionType?: string;
    inspectorId?: string;
    nextInspectionDate?: Date;
    receivedDate?: Date;
    receivedDifference?: Date;
    reducedFee?: boolean;
    registrationId?: number;
    registrationNumber?: number;
    reviewedBy?: string;
    reviewerApproved?: boolean;
    siteName?: string;
    supervisorApproved?: boolean;
    tubeId?: number;
  }) {
    this.baselineDate = options.baselineDate || new Date();
    this.classification = options.classification || '';
    this.comments = options.comments || '';
    this.compliant = options.compliant || false;
    this.controlNumber = options.controlNumber || '';
    this.createdBy = options.createdBy || '';
    this.discountDeadline = options.discountDeadline || new Date();
    this.discountDifference = options.discountDifference || new Date();
    this.documents = options.documents || [];
    this.facilityForm = options.facilityForm || false;
    this.frequency = options.frequency || null;
    this.globalId = options.globalId || '';
    this.id = options.id || null;
    this.inspectionDate = options.inspectionDate || new Date();
    this.inspectionType = options.inspectionType || '';
    this.inspectorId = options.inspectorId || '';
    this.nextInspectionDate = options.nextInspectionDate || new Date();
    this.receivedDate = options.receivedDate || new Date();
    this.receivedDifference = options.receivedDifference || new Date();
    this.reducedFee = options.reducedFee || false;
    this.registrationId = options.registrationId || null;
    this.registrationNumber = options.registrationNumber || null;
    this.reviewedBy = options.reviewedBy || '';
    this.reviewerApproved = options.reviewerApproved || false;
    this.siteName = options.siteName || '';
    this.supervisorApproved = options.supervisorApproved || false;
    this.tubeId = options.tubeId || null;
  }
}
